// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWl8osep1DlEW79_4R2bu41by2kSlu8FI',
    appId: '1:542291232638:web:b085c75ed0f2feaa5dd52f',
    messagingSenderId: '542291232638',
    projectId: 'quizzle-5e2d0',
    authDomain: 'quizzle-5e2d0.firebaseapp.com',
    storageBucket: 'quizzle-5e2d0.appspot.com',
    measurementId: 'G-GJ6X0PWR2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBScZUtnx5jwP-ffckPBXZYJhZ2ctuJFgg',
    appId: '1:542291232638:android:b9cc44cf35793edd5dd52f',
    messagingSenderId: '542291232638',
    projectId: 'quizzle-5e2d0',
    storageBucket: 'quizzle-5e2d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiH8UdT3U9hN_7Hz8vmHZRYZycWLpwBfI',
    appId: '1:542291232638:ios:68b1496b94781c705dd52f',
    messagingSenderId: '542291232638',
    projectId: 'quizzle-5e2d0',
    storageBucket: 'quizzle-5e2d0.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiH8UdT3U9hN_7Hz8vmHZRYZycWLpwBfI',
    appId: '1:542291232638:ios:5dcb0dd5428f8f0f5dd52f',
    messagingSenderId: '542291232638',
    projectId: 'quizzle-5e2d0',
    storageBucket: 'quizzle-5e2d0.appspot.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
